name: Deploy Latest Allure Report

on:
  push:
    branches: [ main ]
    paths: [ 'allure-report_*/**' ]
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find latest report
        id: find-report
        run: |
          latest=$(ls -td allure-report_* | head -1)
          echo "latest_report=$latest" >> $GITHUB_OUTPUT
          echo "Found latest report: $latest"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ steps.find-report.outputs.latest_report }}"

      - name: Deploy
        uses: actions/deploy-pages@v4
